### ISSUE TITLE
Q: How to handle non value-type properties

### ISSUE THREAD

**Issue by KingKnecht** [outbred/URF#1]
Hi,
have you ever faced the problem when a property is not of a value type but a reference type?
The problem here is that the reference type would be stored internally but is still available outside and thus could be modified.

Do you have any thoughts on this?

Best regards,
Sven

**Comment by outbred** [comment]
That reference type (if you want to observe changes to it and make them undoable) would need to inherit from the TrackableViewModelBase.  All of its changes would then get rolled up in the current scope for undo/redo.  If the (local) scope changed on the parent viewmodel, it would need to push down that change to the nested viewmodel, of course.

This is a very common scenario b/c any real-world app will have nested types.  Let me know if the demo needs more examples of this, but I think there's something in there already.

**Comment by KingKnecht** [comment]
Thanks for your quick answer, this helped.
In meantime I was able to test a little bit and to get some promising results. I'm really excited to dig deeper.
I think I wrote at least 3 different undo/redo "frameworks" myself. But none of them was so elegant written and well working.
